services:
  - type: web
    name: agricien-ui-displays
    env: python
    # Usar una versión moderna de python para asegurar la paquetería de Flet
    pythonVersion: 3.11.4
    # Comando de instalación automático
    buildCommand: pip install -r requirements.txt
    # Comando que arranca el webserver configurado en main.py (host=0.0.0.0)
    startCommand: python main.py
